server:
  port: 8080

spring:
  application:
    name: 系统_byLNz


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demosys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Root@123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: DemoSysHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  # ===================== JPA =====================
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # ===================== MVC / JSON =====================
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# ===================== MyBatis =====================
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.demosys.domain.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

# ===================== Spring Security / JWT =====================
security:
  jwt:
    secret: "demo-dev-secret-please-change-32chars-min"
    ttl-seconds: 7200

# ===================== Springdoc OpenAPI =====================
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# ===================== Logging =====================
logging:
  level:
    root: INFO
    com.example.demosys: DEBUG
    org.mybatis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

storage:
  provider: local   # local | minio
  local:
    base-dir: ./data/files
  minio:
    endpoint: http://127.0.0.1:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: demosys
